[package]
name = "cronet-mobile-e2e-runner"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
publish = false

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
tokio-cronet = { path = "../../../crates/tokio-cronet", default-features = false }
futures-core = "0.3"
tokio = { version = "1.44", features = ["io-util", "rt-multi-thread", "sync", "time"] }

[features]
static = ["tokio-cronet/static"]

[workspace]
