[package]
name = "cronet-ohos-e2e-runner"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
cronet = { path = "../../../crates/cronet" }
futures-core = "0.3"
tokio = { version = "1.44", features = ["io-util", "rt-multi-thread", "sync", "time"] }

[features]
static = ["cronet/static"]

[workspace]
