#!/usr/bin/env python3
"""Create a gclient DEPS file containing only explicitly allowed entries."""

import argparse
import ast
from pathlib import Path


PASSTHROUGH_ASSIGNMENTS = (
    "git_dependencies",
    "gclient_gn_args_file",
    "gclient_gn_args",
    "vars",
    "allowed_hosts",
)


def source_value(source: str, assignment: ast.Assign) -> str:
    value = ast.get_source_segment(source, assignment.value)
    if value is None:
        raise ValueError(
            f"could not recover value for {assignment.targets[0].id}"
        )
    return value


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("allow", nargs="+")
    args = parser.parse_args()

    source = args.input.read_text(encoding="utf-8")
    module = ast.parse(source, filename=str(args.input))
    assignments: dict[str, ast.Assign] = {}
    for statement in module.body:
        if (
            isinstance(statement, ast.Assign)
            and len(statement.targets) == 1
            and isinstance(statement.targets[0], ast.Name)
        ):
            assignments[statement.targets[0].id] = statement

    deps_assignment = assignments.get("deps")
    if deps_assignment is None or not isinstance(deps_assignment.value, ast.Dict):
        raise ValueError("upstream DEPS does not contain a literal deps dictionary")

    selected: list[tuple[str, str]] = []
    for key_node, value_node in zip(
        deps_assignment.value.keys, deps_assignment.value.values
    ):
        if not isinstance(key_node, ast.Constant) or not isinstance(
            key_node.value, str
        ):
            continue
        if not any(
            key_node.value.startswith(rule[:-1])
            if rule.endswith("*")
            else key_node.value == rule
            for rule in args.allow
        ):
            continue
        key = ast.get_source_segment(source, key_node)
        value = ast.get_source_segment(source, value_node)
        if key is None or value is None:
            raise ValueError(f"could not recover dependency {key_node.value}")
        selected.append((key, value))

    if not selected:
        raise ValueError("dependency allow-list selected no entries")

    lines = [
        "# Generated by cronet-rs/xtask/filter_deps.py; do not edit.",
        "# All values and revisions below come directly from Chromium's DEPS.",
        "",
    ]
    for name in PASSTHROUGH_ASSIGNMENTS:
        assignment = assignments.get(name)
        if assignment is not None:
            lines.extend((f"{name} = {source_value(source, assignment)}", ""))

    lines.append("deps = {")
    for key, value in selected:
        lines.append(f"  {key}: {value},")
    lines.extend(
        (
            "}",
            "",
            "# Building the library needs no browser hooks or recursive checkouts.",
            "hooks = []",
            "recursedeps = []",
            "",
        )
    )
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"selected {len(selected)} of {len(deps_assignment.value.keys)} dependencies")


if __name__ == "__main__":
    main()
